name: Preprocessing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas scikit-learn

    - name: Run preprocessing
      run: |
        python preprocessing/automate_Kornel.py

    - name: Commit results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add preprocessing/Student_Performance_preprocessing.csv
        git commit -m "Update processed data via GitHub Actions" || echo "No changes to commit"
        git push
